# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.2
        environment:
          FLASK_ENV: testing
          FLASK_APP: run.py
          TEST_DATABASE_URI: postgresql://root@localhost/circle_test
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image: circleci/postgres:9.6.5-alpine-ram
        environment: # environment variables for the Postgres container.
          SECRET_KEY: "!!secret234567890"
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    working_directory: ~/SENDIT-API

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install

        
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            pipenv run tox

      - store_artifacts:
          path: test-reports
          destination: test-reports
